### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by jdkato** [ValeLint/homebrew-vale#1]
We currently install a pre-built binary, which isn't ideal.

**Comment by issyl0** [comment]
The from-source Homebrew formula is now live and installable with `brew install vale`. So this is done?

**Comment by jdkato** [comment]
Yes, thanks for submitting the PR.

My plan now, I suppose, is to update the docs (here and at the main repo) to suggest using the new formula but to leave this repository otherwise untouched. 

Is that the recommended approach for deprecating a tap?

**Comment by issyl0** [comment]
No problem - happy to help!

There's a `tap_migrations.json` file you can put in the root of this repo that, when people install Vale, it will say `Warning: Use vale instead of deprecated ValeLint/vale/vale` and install from the specified migrated tap instead.
